version: "3"

volumes:
  postgres_db_dev: {}

services:
  nginx:
    image: nginx
    container_name: nginx_service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - django
  postgres:
    container_name: postgres_service
    image: postgres:9.5
    volumes:
      - postgres_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=butfit
      - POSTGRES_USER=fitadmin
      - POSTGRES_PASSWORD=butfitseoul
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
  django:
    container_name: django_service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_DB=butfit
      - POSTGRES_USER=fitadmin
      - POSTGRES_PASSWORD=butfitseoul
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - .:/home
    working_dir: /home/butfit

    # 아래 command에 들어가야 한다.

    command: >
      bash -c "
      chmod +x /wait-for-it.sh
      && /wait-for-it.sh postgres:5432 -t 10
      && python3 manage.py migrate
      && gunicorn --bind 0.0.0.0:8000 butfit.wsgi:application"

    # 호스트 OS와 컨테이너의 포트를 바인딩
    # && python3 manage.py migrate
    #   && python3 manage.py runserver
    ports:
      - "8000:8000"
    # 호스트 OS에 포트를 공개하지 않고 컨테이너만 포트를 공개 (현재는 주석)
    #expose :
    # - "8000"
