# Generated by Django 3.2.12 on 2022-03-13 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0002_lesson_credit_earned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_change', models.IntegerField(default=0)),
                ('reason', models.CharField(choices=[('충전', '크레딧충전'), ('구매', '수업구매'), ('환불', '수업환불')], max_length=2)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['log_date'],
            },
        ),
        migrations.CreateModel(
            name='Lessonlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_change', models.IntegerField(default=0)),
                ('reason', models.CharField(choices=[('구매', '수업구매'), ('환불', '수업환불')], max_length=2)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson')),
            ],
            options={
                'ordering': ['log_date'],
            },
        ),
    ]
