# Generated by Django 3.2.12 on 2022-03-13 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0003_alter_lesson_participation'),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='lesson',
            field=models.ForeignKey(db_column='lesson', null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
        ),
        migrations.AlterField(
            model_name='lessonlog',
            name='lesson',
            field=models.ForeignKey(db_column='lesson', on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
