# Generated by Django 3.2.12 on 2022-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20220313_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlog',
            name='reason',
            field=models.CharField(choices=[('구매', '수업구매'), ('환불', '수업환불'), ('생성', '수업생성')], max_length=2),
        ),
        migrations.AlterField(
            model_name='userlog',
            name='reason',
            field=models.CharField(choices=[('생성', '유저생성'), ('충전', '크레딧충전'), ('구매', '수업구매'), ('환불', '수업환불')], max_length=2),
        ),
    ]
