# Generated by Django 3.2.12 on 2022-03-14 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20220313_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonlog',
            options={'ordering': ['-log_date']},
        ),
        migrations.AlterModelOptions(
            name='userlog',
            options={'ordering': ['-log_date']},
        ),
    ]
