# Generated by Django 3.2.12 on 2022-03-11 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('lesson_type', models.CharField(choices=[('유산소', '유산소운동'), ('근력', '근력운동')], max_length=3)),
                ('price', models.DecimalField(decimal_places=0, max_digits=6)),
                ('personnel', models.DecimalField(decimal_places=0, max_digits=2)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('participation', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['location'],
            },
        ),
    ]
