# Generated by Django 3.2.12 on 2022-03-13 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='credit_earned',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
