# Generated by Django 3.2.12 on 2022-03-13 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lesson', '0003_alter_lesson_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='participation',
            field=models.ManyToManyField(blank=True, db_column='participation', related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
